runtime:
  cache_dir: ./.cache/antora

site:
  title: DevNation Workshop - ArgoCD
  start_page: mad-dev-guides-m4::index.adoc

content:
  sources:
    - url: .
      branches: main
      start_path: documentation

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    openshift-password: openshift
  extensions:
    - ./lib/remote-include-processor.js
    - ./lib/tab-block.js

ui:
  bundle:
    url: https://github.com/danieloh30/course-ui/raw/main/ui-bundle-fix-rexp.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./gh-pages
